title: marble Nodes
description: A personal knowledge base built with Jekyll
baseurl: "/marbleNodes"
url: "https://dduyg.github.io"

collections:
  notes:
    output: true
    permalink: /notes/:title/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
      published: true

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
