title: Marble Matrix
description: A personal knowledge base built with Jekyll
baseurl: "/marbleMatrix" # change this if your repo name changes
url: "https://dduyg.github.io"

collections:
  notes:
    output: true
    permalink: /notes/:title/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
      published: true

permalink: pretty
